@base_url = http://localhost:5256/F1

### Teste raiz da API
GET http://localhost:5256

### Cadastrar equipes
POST {{base_url}}/equipes/cadastrar
Content-Type: application/json

{
    "nome" : "RedBull",
    "paisOrigem" : "Australia",
    "dataFundacao":    "2004-06-18"

}
###
POST {{base_url}}/equipes/cadastrar
Content-Type: application/json

{
    "nome" : "Ferrari",
    "paisOrigem" : "Italia",
    "dataFundacao":    "1929-09-13"

}
###
POST {{base_url}}/equipes/cadastrar
Content-Type: application/json

{
  "nome" : "Mercedes",
  "paisOrigem" : "Alemanha",
  "dataFundacao":    "2010-11-16"

}
### Cadastrar pilotos
POST {{base_url}}/pilotos/cadastrar
Content-Type: application/json

{
    "nome" :"Verstappen",
    "nacionalidade" : "Holandês",
    "equipeId" : 1

}
###
POST {{base_url}}/pilotos/cadastrar
Content-Type: application/json

{
    "nome" :"Hamilton",
    "nacionalidade" : "Britânico",
    "equipeId" : 1

}
###
POST {{base_url}}/pilotos/cadastrar
Content-Type: application/json

{
    "nome" :"Leclerc",
    "nacionalidade" : "Monegasco",
    "equipeId" : 2

}
### Listar equipes
GET {{base_url}}/equipes/listar

### Listar pilotos
GET {{base_url}}/pilotos/listar

### Buscar equipe pelo nome
GET {{base_url}}/equipes/buscar/RedBull

### Buscar piloto pelo nome
GET {{base_url}}/pilotos/buscar/Verstappen

### Alterar equipe pelo nome
PUT {{base_url}}/equipes/alterar/Ferrari
Content-Type: application/json

{
    "nome" : "Scuderia Ferrari",
    "paisOrigem" : "Italia",
    "dataFundacao":    "1929-09-13"

}

### Alterar piloto pelo nome
PUT {{base_url}}/pilotos/alterar/Verstappen
Content-Type: application/json

{

    "nome" :"Verstappen",
    "nacionalidade" : "Holandes",
    "equipeId" : 2

}

### deletar equipe pelo nome
DELETE {{base_url}}/equipes/deletar/RedBull

### deletar piloto pelo nome
DELETE {{base_url}}/pilotos/deletar/Verstappen
