// <auto-generated />
using System;
using F1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("F1.Models.Equipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("criadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("dataFundacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("paisOrigem")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("F1.Models.Piloto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("criadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("equipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nacionalidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("equipeId");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("F1.Models.Piloto", b =>
                {
                    b.HasOne("F1.Models.Equipe", "equipe")
                        .WithMany("pilotos")
                        .HasForeignKey("equipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("equipe");
                });

            modelBuilder.Entity("F1.Models.Equipe", b =>
                {
                    b.Navigation("pilotos");
                });
#pragma warning restore 612, 618
        }
    }
}
